/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
/* 侧边栏设置官方指导：https://docusaurus.io/zh-CN/docs/sidebar */
 
// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  exampleSidebar: [   
	{type: 'autogenerated', dirName: 'example'},
  ],
  
  itnote: [
    {type: 'autogenerated', dirName: 'itnotes'},
  ],
  
  other: [
    {type: 'autogenerated', dirName: 'others'}
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
